version: "3.1"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - ./bkpsql:/usr/sql
      - ./init:/docker-entrypoint-initdb.d


# GET id container 
# docker ps 

# Entra no container com  CONTAINER ID 
# docker exec -it CONTAINERID bash

# mysql -uroot -proot DATABASENAME < /usr/sql/[name].sql

# Subir a base no container
# mysql -uroot -pMySql2020! sapienDesenv < /usr/sql/[name].sql

# Libera o usuario para atuar no banco
# GRANT ALL ON *.* TO 'someuser'@'%' IDENTIFIED BY 'complex-password';
# FLUSH PRIVILEGES;